//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateMvvmLight.AppResources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemplateMvvmLight.AppResources.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string COPYRIGHT_TEXT {
            get {
                return ResourceManager.GetString("COPYRIGHT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DETAILS_TITLE {
            get {
                return ResourceManager.GetString("DETAILS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenziali errate.
        /// </summary>
        public static string ERROR_BAD_CREDENTIALS {
            get {
                return ResourceManager.GetString("ERROR_BAD_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore, riprovare più tardi.
        /// </summary>
        public static string ERROR_GENERIC {
            get {
                return ResourceManager.GetString("ERROR_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllare la connessione del dispositivo e riprovare.
        /// </summary>
        public static string ERROR_NO_CONNECTIVITY {
            get {
                return ResourceManager.GetString("ERROR_NO_CONNECTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticazione fallita.
        /// </summary>
        public static string ERROR_TITLE_AUTHENTICATION {
            get {
                return ResourceManager.GetString("ERROR_TITLE_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        public static string ERROR_TITLE_GENERIC {
            get {
                return ResourceManager.GetString("ERROR_TITLE_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore di rete.
        /// </summary>
        public static string ERROR_TITLE_NETWORK {
            get {
                return ResourceManager.GetString("ERROR_TITLE_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME_TITLE {
            get {
                return ResourceManager.GetString("HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticazione in corso.
        /// </summary>
        public static string LOADING_AUTHENTICATION {
            get {
                return ResourceManager.GetString("LOADING_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LOGIN_PASSWORD_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_PASSWORD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accedi.
        /// </summary>
        public static string LOGIN_SUBMIT_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_SUBMIT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN_USERNAME_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_USERNAME_TEXT", resourceCulture);
            }
        }
    }
}
